### ISSUE TITLE
filtering projections

### ISSUE THREAD

**Issue by softprops** [dispatch/reboot#37] opened 2013-01-28 04:57 UTC
One thing I'd like to be able to do is to operate on promise projections is to do something like

``` scala
def req = url("http://api.meetup.com/2/member/self")
for { JObject(fs) <- Http(req > as.lift.Json).either.right }
 yield fs
```

If I try to do this with the current release the compiler tells me that the projection doesn't implement filter method.

I took some [inspiration for scala's projections](https://github.com/scala/scala/blob/v2.10.0/src/library/scala/util/Either.scala#L549-L552) and added what I thought would work in a [new branch](https://github.com/dispatch/reboot/commit/42c5210ebbd8fca0d5c86c2ea91d27b9643dccb5)

This doesn't quiet do what I thought it may be I wanted to get your thoughts before I go further.

Testing this in the liftjson module I get this error

``` scala
scala> (for { JObject(fs) <- Http(url("http://api.meetup.com/2/member/self") OK as.lift.Json).either.right } yield fs)()
<console>:17: error: constructor cannot be instantiated to expected type;
 found   : net.liftweb.json.JsonAST.JObject
 required: Option[Either[Nothing,net.liftweb.json.package.JValue]]
              (for { JObject(fs) <- Http(url("http://api.meetup.com/2/member/self") OK as.lift.Json).either.right } yield fs)()
```

It's very possible that I'm not unraveling something correctly. The filter method I added to the PromiseEither Left/Right projections seems in line with those same definitions in scala's left/right projections.

**Comment by farmdawgnation** [comment] 2017-07-03 17:08
My impression from reading this issue is that this isn't something that's still a problem given that we dropped support for older Scala versions, but I could be wrong about that. I'll leave it unlabled for now as a signal to myself to investigate further. If someone could validate my understanding I could just close this issue.

**Comment by farmdawgnation** [comment] 2017-07-05 19:50
Just confirmed this is still an issue as written, but that seems to be because of the conflation of `Future` and `Either`, which I'm not sure _should_ be supported in any event. FWIW, Scala 2.12 introduced `toTry` on `Either` that allows something like this:

```scala
@ for { result <- Http(req > as.lift.Json).either } yield {
    for ( JObject(fs) <- result.toTry ) yield fs
  }
res8: Future[scala.util.Try[List[JField]]] = Future(<not completed>)
@ res8.value
res9: Option[scala.util.Try[scala.util.Try[List[JField]]]] = Some(
  Success(
    Success(
      List(
        JField("details", JString("API requests must be key-signed, oauth-signed, or accompanied by a key: https://www.meetup.com/meetup_api/docs/#authentication")),
        JField("code", JString("not_authorized")),
        JField("problem", JString("You are not authorized to make that request"))
      )
    )
  )
)
```

To that end, since we no longer support < 2.11, we should probably expose a helper to provide a `Try` instead of an `Either` if that's what folks want in their code.

I'm going to close this issue and open a new ticket for `Try` support from the execution system. Let me know if there are any concerns with this resolution.

**Closed by farmdawgnation** 2017-07-05 19:50 UTC
